kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: "josh-cluster"
  region: "us-west-2"
  version: "1.20"
  tags:
    "Name": "josh-cluster"
    "creator": "josh.lee"
    "protected": "weekend"

vpc:
  nat:
    gateway: Single
  subnets:
    private:
      us-west-2a:
        id: subnet-09545f79a52f59825
      us-west-2b:
        id: subnet-0df0c7239150dd441
      us-west-2c:
        id: subnet-067d25b121cf77310
    public: {}
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

nodeGroups:
- name: linux-default
  privateNetworking: true
  amiFamily: AmazonLinux2
  spotOcean: {}

cloudwatch:
  clusterLogging:
    enableTypes:
      - "api"
      - "audit"
      - "authenticator"

addons:
  gitops:
    flux:
      gitProvider: github
      flags:
        owner: joshdlee
        repository: eks-fluxcd-bootstrap
        branch: main
        path: ./clusters/josh-cluster/
        namespace: flux-system